
//https://stackoverflow.com/questions/66798159/on-insert-or-update-i-want-to-update-updated-at-column-with-current-timestamp
https://docs.oracle.com/cd/E17952_01/mysql-5.7-en/timestamp-initialization.html

CREATE TABLE Employees(
 EMP_ID    NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
 EMP_FIRST_NAME VARCHAR(50) NOT NULL,
 EMP_LAST_NAME VARCHAR(50) NOT NULL,
 EMP_CITY VARCHAR(50) NOT NULL,
 CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 MODIFIED_BY VARCHAr(20) DEFAULT USER ,
 PRIMARY KEY ( EMP_ID)
)

create trigger set_updated_at
  before update on Employees
  for each row
begin
  :new.updated_at := current_timestamp();
end;

INSERT INTO Employees(EMP_FIRST_NAME, EMP_LAST_NAME, EMP_CITY)
VALUES ('Rishabh','Puri','pune');

SELECT * from employees;

